### PR TITLE
Cannot add bucket to a Namespace with no buckets

### LINKED ISSUE #99: Cannot add bucket to a Namespace with no buckets
### Description
If a namespace has no buckets, then adding a bucket fails using REST endpoint `/api/{namespace_name}/{bucket_name}`

### Reproduction Steps
1. Create an empty namespace or remove buckets from a namespace until there are no buckets remaining.
2. Add a bucket to namespace
3. Bucket does not get added

### Details
Behind the scenes quotaservice is trying to add a bucket to a nil map.
This is happening because `CreateBucket` in `config/mutable.go` is passed a clone of the service config's proto. Empty maps are not initialized.

### PR DESCRIPTION
**Pull request by sajidsnasir**
fixes #99

### CODE REVIEW

File: config/mutable_test.go [hunk 1]
```diff
@@ -43,10 +43,19 @@ func TestGlobalCreateBucket(t *testing.T) {
 }
 
 func TestCreateBucket(t *testing.T) {
-	cfg := defaultConfig()
+	nilMapBucketsCfg := defaultConfig()
```
Comment (maniksurtani) [inline config/mutable_test.go]: Can we make this a separate test function? E.g., `func TestCreateBucketInEmptyNamespace`?
